name: meek_warrior
favicon: null
layout_spectrum: 0.25543
typography_spectrum: 0.7708516921848059
title: 'Meek Warrior '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#160f1f'
    - '#219ea5'
    - '#1d4a67'
    - '#27717f'
    - '#68cfa6'
  brandStrength: 0.7521541444584727
  lightness: 0.2790881930850446
  saturation: 0.8979869761969894
  rhythmicContrast: 0.8615408283658326
purpose: []
